# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-13 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KhanAcademyVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=255)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('tutorial', models.CharField(max_length=255)),
                ('priority', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('language', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='khanacademyvideo',
            name='youtube_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='translations.YoutubeVideo'),
        ),
    ]
