# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-20 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_auto_20170311_0618'),
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[(b'subtitle', b'Subtitle translation'), (b'subtitle_review', b'Subtitle review'), (b'voiceover', b'Voiceover'), (b'voiceover_review', b'Voiceover review')], db_index=True, max_length=30)),
                ('state', models.CharField(choices=[(b'assigned', b'Assigned'), (b'abandoned', b'Abandoned'), (b'completed', b'Completed')], db_index=True, max_length=30)),
                ('language', models.CharField(default=b'ta', max_length=3)),
                ('comment', models.CharField(blank=True, max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='khanacademyvideo',
            name='youtube_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='translations.YoutubeVideo'),
        ),
        migrations.AddField(
            model_name='task',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translations.KhanAcademyVideo'),
        ),
        migrations.AddField(
            model_name='task',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.Volunteer'),
        ),
    ]
