# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-11 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
